// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.

// Example:
// Input:
// s = "abcd"
// t = "abcde"
// Output:
// e

// Explanation:
// 'e' is the letter that was added.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = (s, t) => {
    s = s.split('').sort();
    t = t.split('').sort();
    for (let i = 0; i < t.length; i++) {
        if (t[i] !== s[i]) return t[i];
    }
};

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = (s, t) => {
    if (!s) return t;
    let sSum = 0;
    let tSum = 0;
    for (let i = 0; i < s.length; i++) sSum += s.charCodeAt(i);
    for (let i = 0; i < t.length; i++) tSum += t.charCodeAt(i);
    return String.fromCharCode(tSum - sSum);
};

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = (s, t) => {
    if (!s) return t;
    let r = s.charCodeAt(0);
    for (let i = 1; i < s.length; i++) r ^= s.charCodeAt(i);
    for (let i = 0; i < t.length; i++) r ^= t.charCodeAt(i);
    return String.fromCharCode(r);
};